language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

services:
    - mysql
    - postgresql

before_install:
  - composer install
  - cd tests

before_script:
 # - psql -c "DROP DATABASE IF EXISTS patabaseTest;" -U postgres
 # - mysql -e "DROP DATABASE IF EXISTS patabaseTest;" -uroot

script: 
  - ../vendor/bin/phpunit --debug --configuration phpunit.xml --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
